### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by kormilitzin** [explosion/spacy-llm#223]
Hi all, I installed spacy 3.6 and spacy-llm 0.4.2, however, when tried to import spacy_llm, I got the segmentation fault error:

![Screenshot 2023-07-17 at 21 32 01](https://github.com/explosion/spacy-llm/assets/20815939/735f1415-2279-46cc-85be-d5d4e73eef1e)

my system:

## Info about spaCy

- **spaCy version:** 3.6.0
- **Platform:** Linux-5.4.0-148-generic-x86_64-with-glibc2.27
- **Python version:** 3.11.3
- **Pipelines:** en_core_web_lg (3.6.0), en_core_web_sm (3.6.0), en_core_web_trf (3.6.1)

Any ideas, please?

**Comment by rmitsch** [comment]
Hi @kormilitzin! How exactly did you install spaCy? Did you install it in a clean/new virtual environment?

**Comment by kormilitzin** [comment]
@rmitsch thank you. I created a new fresh virtual environment and installed packages.

Specifically:

```
python3.11 -m venv spacy-llm
(spacy-llm) pip install -U pip
(spacy-llm) pip install -U setuptools wheel
(spacy-llm) pip install torch torchvision torchaudio
(spacy-llm) pip install -U 'spacy[cuda-autodetect,transformers,lookups]'
(spacy-llm) pip install -U spacy-llm
```
all worked well. However, when I wanted to use `spacy_llm` I got segfault. Shall I remove this virtual env. and re-install again? Do I need to install `torch` first?

**Comment by rmitsch** [comment]
Thanks for the write-up. Could you please post the entire stack trace?

**Comment by Lolologist** [comment]
@kormilitzin , a thought from some recent trouble I had; are you using torch>=2.0? In *some* VMs I have to use <2.
