### ISSUE TITLE
Few-shot limiations problem (textcat_openai)

### ISSUE THREAD

**Issue by JayBroe** [explosion/spacy-llm#228]
Hi,
according to example with [https://github.com/explosion/spacy-llm/tree/main/usage_examples/textcat_openai](url) I tried to add more data in case of few-shot training. Unfortunately, according to openai token limitations, My request cannot be accepted.

used model: Ada (of course I know that there are better options, but none of them has a super-large token capacity)

**ERROR:

ValueError: Request to OpenAI API failed: This model's maximum context length is 2049 tokens, however you requested 83753 tokens (83737 in your prompt; 16 for the completion). Please reduce your prompt; or completion length.**

I crossed the whole internet and I still haven't received any solution. Every
similiar problem is described accordingly to the summarization task.
My question is: is there a solution for chunking JSON files which provide the few-shot learning
available for the code from this repository? Ore there exists any different correct idea?

**I installed spaCy correctly and there are no problems with 
my openai api key.**

I will be thankful for any help!

**Comment by rmitsch** [comment]
Hi @JayBroe, that's a limitation of the model that we can't do anything about. I recommend looking up other models, OpenAI provides a 32k version of GPT-4.

If you really need ~80 tokens, your only option at the moment AFAIK is Anthropic's Claude and Claude-2 in their 100k versions.

Note that you can use all of these models in `spacy-llm`: 
```ini
[components.llm.model]
@llm_models = "spacy.GPT-4.v1"
name = "gpt-4-32k"
```
or
```ini
[components.llm.model]
@llm_models = "spacy.Claude-1.v1"
name = "claude-1-100k"
```

Note: a `spacy-llm` version supporting Claude-2 hasn't been released yet, but this will happen probably today.
