### ISSUE TITLE
FewShot Learning-spacy-llm

### ISSUE THREAD

**Issue by VK-T** [explosion/spacy-llm#276]
Hi,

This issue is all about the fewshot learning challenges by using Dolly LLM for NER approach.

**Task and model used:**
`[components.llm.task]
@llm_tasks = "spacy.NER.v2"
labels = BATTERY_CAPACITY_KWH,BODY_TYPE,NUMBER_OF_DOORS,DRIVEN_WHEELS,ENGINE_SIZE,FUEL_TYPE,MAKE,MAX_POWER_KW,MAX_POWER_HP,MODEL,POWER_TRAIN_TYPE,TRANSMISSION,TRIM_LEVEL,SECONDARY_VERSION

[components.llm.model]
@llm_models = "spacy.Dolly.v1"
name = "dolly-v2-3b"`

**With GPU:**
	**Case-1: Few-shot Learning with single example**
          As per spacy-llm NER concept, to make the LLM model (Dolly) to predict for a custom data, requires sending the example which contains version name and it's respective entities. Prepared an example file in .yaml format. spacy accepts the example file and created the pipeline for prediction. 
          Consider a text. On first execution, no prediction at all. In the next execution of the same text, two or three entities got predicted. In the third execution, either prediction of 5 entities or no prediction. This is unstable if I need to work on 5k data.
      **Case-2: Few-shot Learning with more than one example**
      Created a .yaml and .yml  file with **more than one example and it's respective entities**. While running the script, the error message "File formats are not supported" popping out. Cross checked the files against the file formats available in github where there is no any issues with the files I had created. Also, checked the video of Vincent's spacy-llm explanation. Even tried the same, facing the same "file formats not supported"

  1.  format of .yaml file as per video [](https://www.youtube.com/watch?v=zEu-ZJz0NOo&t=601s) :
       
       ![image](https://github.com/explosion/spacy-llm/assets/89963398/fb6934d2-3d68-4e24-8a23-d4ac384036cc)

  2.  format of .yml file as per spacy-llm's github example.yml:

      ![image](https://github.com/explosion/spacy-llm/assets/89963398/8c73c854-ff50-4cfe-965f-f9b15e7d16a0)

  3. format of JSONL , tried as per examples provided in re_openai folder where considered only text and ents keys. faced below error:
     
![image](https://github.com/explosion/spacy-llm/assets/89963398/0734127b-3ff7-48bb-81dd-a9a3b43269fa)

with respect to CPU, will the prediction for a text takes more than 10 mins? Because for single piece of text (contains not more than 20 words), tooks more than 10 mins.

**Comment by rmitsch** [comment]
Hi @VK-T! For future consideration: please open one issue per problem. This will help other users find and iden

> Consider a text. On first execution, no prediction at all. In the next execution of the same text, two or three entities got predicted. In the third execution, either prediction of 5 entities or no prediction. This is unstable if I need to work on 5k data.

Some notes on that:
- Dolly 2 with 3B is a rather small model. Try a larger Dolly variant, this should be more accurate.
- LLMs can be more inconsistent in their predictions than local models. Ensure that the temperature parameter is set to 0 to force the model to be consistent as possible in its output.
- We test all our prompts on GPT-3.5, but at the moment we can't guarantee that the prompts work just as well for all models we offer. This is in our roadmap. Consider experimenting with different prompts for your chosen model and use them instead, if they work better (by adapting the config).

> While running the script, the error message "File formats are not supported" popping out.

Which `spacy-llm` version are you using? We test the provided examples in our CI, so these should work.

> with respect to CPU, will the prediction for a text takes more than 10 mins? Because for single piece of text (contains not more than 20 words), tooks more than 10 mins.

LLMs are very inefficient to run on CPUs. We recommend using GPUs.

**Comment by VK-T** [comment]
Hi @rmitsch , 

1. Tried with Dolly 7b with/without Fewshot Learning for a custom data, no prediction at all.
2. Is spacy-llm well compatible with Google Colab?
3. spacy-llm version used is 0.4.3

**Comment by rmitsch** [comment]
1. I recommend experimenting the prompt. Cross-model prompt compatibility is on our roadmap.
2. Yes.
3. Can you upload a minimal, reproducible example? This works for me with 0.4.3.
4. Yes, any task/model combination is possible (although it's not guaranteed at this point processes the prompt properly if it's not GPT 3.5+, see #1).
