### ISSUE TITLE
DollyV2 not utilizing GPU

### ISSUE THREAD

**Issue by mikeybellissimo** [explosion/spacy-llm#293]
Hi, 
Really excited about using this awesome technology you're all building. I am running some of the example code, specifically the one you put with using DollyV2 for NER described here https://github.com/explosion/spacy-llm/tree/main/usage_examples/ner_dolly . 
Everything runs fine and as expected but when I monitor my GPU utilization, it is clear that it is all running on CPU. 
I have checked to make sure that torch.cuda.is_available() is true and that my 2 devices are listed but it is still not working. Any idea how to force it to use GPU?
Thanks,
Michael

**Comment by rmitsch** [comment]
Hi @mikeybellissimo, thanks for reporting this. Can you provide the full config you're running?

**Comment by mikeybellissimo** [comment]
Let me know if you meant you need the full configuration and not just the config file lol

**Comment by mikeybellissimo** [comment]
Also potentially worth noting that I have two GPUs on my desktop so not sure if that's contributing to the issue.

**Comment by mikeybellissimo** [comment]
Nevermind! I realized that I didn't have cuda-toolkit installed which isn't an issue when I'm using pytorch and transformers directly but this appeared to fix it when I installed. Thank you!

**Comment by rmitsch** [comment]
Thanks for the update!
