### ISSUE TITLE
incompatible - No compatible package found for 'en_core_web_trf_lg' (spaCy v3.6.0

### ISSUE THREAD

**Issue by scrapper2023** [explosion/spacy-llm#294]
✘ No compatible package found for 'en_core_web_trf_lg' (spaCy
v3.6.0)

i have tried using spacy version 3.5.1, 3.6, 3.7 dev(0) none works

**Comment by adrianeboyd** [comment]
This doesn't seem like a question about `spacy-llm`?

The available English pipeline packages are described here: https://spacy.io/models/en
