### ISSUE TITLE
KeyError: 'data' when loading sample config file

### ISSUE THREAD

**Issue by PhysicsBen** [explosion/spacy-llm#296]
I can't seem to load a config file. I have tried some of the examples in the documentation but get the same key error. I assume that I am doing something wrong, but I can't figure out what.

Here is the the full code

```{python}
import os
import yaml

from spacy_llm.util import assemble

with open("config.yaml", 'r') as f:
    config = yaml.safe_load(f)

os.environ["OPENAI_API_KEY"] = config.get('OPENAI_API_KEY')

nlp = assemble("config.cfg")
doc = nlp("You look gorgeous!")
print(doc.cats)
```

Here is the config file:
```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.TextCat.v3"
labels = ["COMPLIMENT", "INSULT"]

[components.llm.model]
@llm_models = "spacy.GPT-4.v2"
```

Full error

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[4], line 1
----> 1 nlp = assemble("config.cfg")
      2 doc = nlp("You look gorgeous!")
      3 print(doc.cats)

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy_llm\util.py:48](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy_llm/util.py:48), in assemble(config_path, overrides)
     46 config_path = Path(config_path)
     47 config = load_config(config_path, overrides=overrides, interpolate=False)
---> 48 return assemble_from_config(config)

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy_llm\util.py:28](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy_llm/util.py:28), in assemble_from_config(config)
     22 def assemble_from_config(config: Config) -> Language:
     23     """Assemble a spaCy pipeline from a confection Config object.
     24 
     25     config (Config): Config to load spaCy pipeline from.
     26     RETURNS (Language): An initialized spaCy pipeline.
     27     """
---> 28     nlp = load_model_from_config(config, auto_fill=True)
     29     config = config.interpolate()
     30     sourced = get_sourced_components(config)

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy\util.py:587](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy/util.py:587), in load_model_from_config(config, meta, vocab, disable, enable, exclude, auto_fill, validate)
    584 # This will automatically handle all codes registered via the languages
    585 # registry, including custom subclasses provided via entry points
    586 lang_cls = get_lang_class(nlp_config["lang"])
--> 587 nlp = lang_cls.from_config(
    588     config,
    589     vocab=vocab,
    590     disable=disable,
    591     enable=enable,
    592     exclude=exclude,
    593     auto_fill=auto_fill,
    594     validate=validate,
    595     meta=meta,
    596 )
    597 return nlp

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy\language.py:1847](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy/language.py:1847), in Language.from_config(cls, config, vocab, disable, enable, exclude, meta, auto_fill, validate)
   1844     factory = pipe_cfg.pop("factory")
   1845     # The pipe name (key in the config) here is the unique name
   1846     # of the component, not necessarily the factory
-> 1847     nlp.add_pipe(
   1848         factory,
   1849         name=pipe_name,
   1850         config=pipe_cfg,
   1851         validate=validate,
   1852         raw_config=raw_config,
   1853     )
   1854 else:
   1855     assert "source" in pipe_cfg

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy\language.py:814](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy/language.py:814), in Language.add_pipe(self, factory_name, name, before, after, first, last, source, config, raw_config, validate)
    810     pipe_component, factory_name = self.create_pipe_from_source(
    811         factory_name, source, name=name
    812     )
    813 else:
--> 814     pipe_component = self.create_pipe(
    815         factory_name,
    816         name=name,
    817         config=config,
    818         raw_config=raw_config,
    819         validate=validate,
    820     )
    821 pipe_index = self._get_pipe_index(before, after, first, last)
    822 self._pipe_meta[name] = self.get_factory_meta(factory_name)

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy\language.py:702](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy/language.py:702), in Language.create_pipe(self, factory_name, name, config, raw_config, validate)
    699 cfg = {factory_name: config}
    700 # We're calling the internal _fill here to avoid constructing the
    701 # registered functions twice
--> 702 resolved = registry.resolve(cfg, validate=validate)
    703 filled = registry.fill({"cfg": cfg[factory_name]}, validate=validate)["cfg"]
    704 filled = Config(filled)

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\confection\__init__.py:756](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/confection/__init__.py:756), in registry.resolve(cls, config, schema, overrides, validate)
    747 @classmethod
    748 def resolve(
    749     cls,
   (...)
    754     validate: bool = True,
    755 ) -> Dict[str, Any]:
--> 756     resolved, _ = cls._make(
    757         config, schema=schema, overrides=overrides, validate=validate, resolve=True
    758     )
    759     return resolved

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\confection\__init__.py:805](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/confection/__init__.py:805), in registry._make(cls, config, schema, overrides, resolve, validate)
    803 if not is_interpolated:
    804     config = Config(orig_config).interpolate()
--> 805 filled, _, resolved = cls._fill(
    806     config, schema, validate=validate, overrides=overrides, resolve=resolve
    807 )
    808 filled = Config(filled, section_order=section_order)
    809 # Check that overrides didn't include invalid properties not in config

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\confection\__init__.py:860](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/confection/__init__.py:860), in registry._fill(cls, config, schema, validate, resolve, parent, overrides)
    858     schema.__fields__[key] = copy_model_field(field, Any)
    859 promise_schema = cls.make_promise_schema(value, resolve=resolve)
--> 860 filled[key], validation[v_key], final[key] = cls._fill(
    861     value,
    862     promise_schema,
    863     validate=validate,
    864     resolve=resolve,
    865     parent=key_parent,
    866     overrides=overrides,
    867 )
    868 reg_name, func_name = cls.get_constructor(final[key])
    869 args, kwargs = cls.parse_args(final[key])

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\confection\__init__.py:877](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/confection/__init__.py:877), in registry._fill(cls, config, schema, validate, resolve, parent, overrides)
    874     getter = cls.get(reg_name, func_name)
    875     # We don't want to try/except this and raise our own error
    876     # here, because we want the traceback if the function fails.
--> 877     getter_result = getter(*args, **kwargs)
    878 else:
    879     # We're not resolving and calling the function, so replace
    880     # the getter_result with a Promise class
    881     getter_result = Promise(
    882         registry=reg_name, name=func_name, args=args, kwargs=kwargs
    883     )

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy_llm\models\rest\openai\registry.py:43](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy_llm/models/rest/openai/registry.py:43), in openai_gpt_4_v2(config, name, strict, max_tries, interval, max_request_time)
     24 @registry.llm_models("spacy.GPT-4.v2")
     25 def openai_gpt_4_v2(
     26     config: Dict[Any, Any] = SimpleFrozenDict(temperature=_DEFAULT_TEMPERATURE),
   (...)
     33     max_request_time: float = OpenAI.DEFAULT_MAX_REQUEST_TIME,
     34 ) -> Callable[[Iterable[str]], Iterable[str]]:
     35     """Returns OpenAI instance for 'gpt-4' model using REST to prompt API.
     36 
     37     config (Dict[Any, Any]): LLM config passed on to the model's initialization.
   (...)
     41     DOCS: https://spacy.io/api/large-language-models#models
     42     """
---> 43     return OpenAI(
     44         name=name,
     45         endpoint=Endpoints.CHAT.value,
     46         config=config,
     47         strict=strict,
     48         max_tries=max_tries,
     49         interval=interval,
     50         max_request_time=max_request_time,
     51     )

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy_llm\models\rest\base.py:65](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy_llm/models/rest/base.py:65), in REST.__init__(self, name, endpoint, config, strict, max_tries, interval, max_request_time)
     62 assert self._max_request_time > 0
     64 self._check_model()
---> 65 self._verify_auth()

File [c:\Users\benja\Code\spacy-llm\env\lib\site-packages\spacy_llm\models\rest\openai\model.py:70](file:///C:/Users/benja/Code/spacy-llm/env/lib/site-packages/spacy_llm/models/rest/openai/model.py:70), in OpenAI._verify_auth(self)
     65     else:
     66         warnings.warn(
     67             f"Error accessing api.openai.com ({r.status_code}): {r.text}"
     68         )
---> 70 response = r.json()["data"]
     71 models = [response[i]["id"] for i in range(len(response))]
     72 if self._name not in models:

KeyError: 'data'

Here is my python env:

Package                   Version
------------------------- ------------
aiohttp                   3.8.5
aiosignal                 1.3.1
annotated-types           0.5.0
anyio                     4.0.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asttokens                 2.4.0
async-lru                 2.0.4
async-timeout             4.0.3
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.0.0
blis                      0.7.10
catalogue                 2.0.9
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.7
colorama                  0.4.6
comm                      0.1.4
confection                0.1.3
cymem                     2.0.8
dataclasses-json          0.5.14
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
en-core-web-lg            3.6.0
exceptiongroup            1.1.3
executing                 1.2.0
fastjsonschema            2.18.0
fqdn                      1.5.1
frozenlist                1.4.0
greenlet                  2.0.2
idna                      3.4
ipykernel                 6.25.2
ipython                   8.15.0
ipython-genutils          0.2.0
ipywidgets                8.1.1
isoduration               20.11.0
jedi                      0.19.0
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            8.3.1
jupyter-console           6.6.3
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
jupyterlab-widgets        3.0.9
langchain                 0.0.292
langcodes                 3.3.0
langsmith                 0.0.37
MarkupSafe                2.1.3
marshmallow               3.20.1
matplotlib-inline         0.1.6
mistune                   3.0.1
multidict                 6.0.4
murmurhash                1.0.10
mypy-extensions           1.0.0
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nest-asyncio              1.5.7
notebook                  7.0.3
notebook_shim             0.2.3
numexpr                   2.8.6
numpy                     1.25.2
overrides                 7.4.0
packaging                 23.1
pandas                    2.1.0
pandocfilters             1.5.0
parso                     0.8.3
pathy                     0.10.2
pickleshare               0.7.5
pip                       23.2.1
platformdirs              3.10.0
preshed                   3.0.9
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
pure-eval                 0.2.2
pycparser                 2.21
pydantic                  2.3.0
pydantic_core             2.6.3
Pygments                  2.16.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3.post1
pywin32                   306
pywinpty                  2.0.11
PyYAML                    6.0.1
pyzmq                     25.1.1
qtconsole                 5.4.4
QtPy                      2.4.0
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
Send2Trash                1.8.2
setuptools                68.2.2
six                       1.16.0
smart-open                6.4.0
sniffio                   1.3.0
soupsieve                 2.5
spacy                     3.6.1
spacy-legacy              3.0.12
spacy-llm                 0.5.1
spacy-loggers             1.0.5
SQLAlchemy                2.0.20
srsly                     2.4.7
stack-data                0.6.2
tenacity                  8.2.3
terminado                 0.17.1
thinc                     8.1.12
tinycss2                  1.2.1
tomli                     2.0.1
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.10.0
typer                     0.9.0
typing_extensions         4.7.1
typing-inspect            0.9.0
tzdata                    2023.3
uri-template              1.3.0
urllib3                   2.0.4
wasabi                    1.1.2
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
wheel                     0.41.2
widgetsnbextension        4.0.9
yarl                      1.9.2

**Comment by PhysicsBen** [comment]
I figured it out. My OpenAI API key was invalid.

**Comment by PhysicsBen** [comment]
I figured it out. My OpenAI API key was invalid.

**Comment by Serega6678** [comment]
Thank you very much :)

**Comment by Serega6678** [comment]
In my case I was doing !export in the notebook but doing os.environ["OPENAI_API_KEY"] = "..." fixed the problem
