### ISSUE TITLE
ValueError: Request to Azure OpenAI API failed: Resource not found

### ISSUE THREAD

**Issue by Hironsan** [explosion/spacy-llm#336]
The error occurs when `model_type` is `chat`.

```plain
[components.llm.model]
@llm_models = "spacy.Azure.v1"
name = "deployment-name"
base_url = "base-url"
model_type = "chat"
api_version = ""
config = {"temperature": 0.0 }
```

In the case of `model_type = "chat"`, I think we need to append `/completions`:

https://github.com/explosion/spacy-llm/blob/5c2b565e52dfd89ab8b6515dd7c14a2bcefad3cd/spacy_llm/models/rest/azure/model.py#L51

References

- [Chat completions](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions)
- [Completions](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions)

**Comment by rmitsch** [comment]
Thanks for reporting this! You're right. Unfortunately we didn't have access chat models on Azure when we added the Azure support, hence this not being properly tested.

We'll release a patch for this soon.

**Comment by rmitsch** [comment]
Fix has been merged, a patch version including this will be released soon.
