### ISSUE TITLE
Provide NER identification

### ISSUE THREAD

**Issue by tianchiguaixia** [explosion/spacy-llm#344]
Indeed, this can solve some NER problems. How to target those parts that cannot be extracted?

1. Is there a method for fine tuning provided

2. Is a knowledge base provided

**Comment by rmitsch** [comment]
Hi @tianchiguaixia, 
- `spacy-llm` doesn't provide any tools for fine-tuning LLMs. For that, I recommend looking into the capabilities of the provider you're using (OpenAI, Anthropic, Cohere, ...) or, correspondingly, open source tools (e. g. [here](https://huggingface.co/docs/autotrain/llm_finetuning)).
- A knowledge base is not part of the NER task, no.

I recommend tackling this by combining the LLM NER task with an [`EntityRuler`](https://spacy.io/api/entityruler) to leverage a rule-based approach if you have prior knowledge about the entities in your data and/or a pretrained spaCy NER (non-LLM) component. This should help catch entities not identified by your LLM.

**Comment by tianchiguaixia** [comment]
Thank you very much, space_ Llm has been very helpful to us
