### ISSUE TITLE
add a NER feature

### ISSUE THREAD

**Issue by tianchiguaixia** [explosion/spacy-llm#370]
Can we add a feature if I don't know the tags I extracted beforehand and rely on the model to understand and structure them.

**Comment by rmitsch** [comment]
Hey @tianchiguaixia. Do I understand correctly that you want to do NER without defining the labels beforehand? `spacy-llm` already supports NER with defined labels.

**Comment by tianchiguaixia** [comment]
Excuse me, could you please provide an example? I couldn't find it.

**Comment by tianchiguaixia** [comment]
I have another question to ask you. How to customize prompts during use, such as how to set prompts in a. cfg file?

**Comment by rmitsch** [comment]
You can find an NER example [here](https://github.com/explosion/spacy-llm/tree/main/usage_examples/ner_v3_openai). Prompts can be customized by passing a modified prompt template file:
```ini
...
[components.llm.task.template]
@misc = "spacy.FileReader.v1"
path = path_to_your_jinja_file.jinja
...
```

**Comment by tianchiguaixia** [comment]
thank you. I'll give this a try. I have been debugging your source code recently: Recently, I have also successfully debugged the method of integrating into the Chinese large model.
