### ISSUE TITLE
Unsupported Langchain models

### ISSUE THREAD

**Issue by florianchappaz** [explosion/spacy-llm#373]
`spacy-llm 0.6.3` comes with the support of `langchain 0.0.335`. 
This version of Langchain comes with many more LLMs that we could potentially use.

In practice, this is not the case. In Langchain, signatures of BaseLanguageModel aren't harmonized. But the current code of `spacy-llm` assumes that every models constructor in Langchain have the parameter `model_name`, which is not true anymore.

Let's take the example of [Ollama](https://python.langchain.com/docs/integrations/llms/ollama). The signature is taking a `model` parameter instead of a `model_name` parameter.

The following config:
```[components.llm.model]
@llm_models = "langchain.Ollama.v1"
name = "llama2"
query = {"@llm_queries": "spacy.CallLangChain.v1"}
config = {"temperature": 0.0}
```
will then leads to errors like 
```
pydantic.error_wrappers.ValidationError: 1 validation error for Ollama
model_name
  extra fields not permitted (type=value_error.extra)
```

I can modify the code to handle those specific cases, but I need some guidance on the decisions:
- For Langchain models, should we let the user indicate the name of the model with the appropriate parameter name within the config?
```
@llm_models = "langchain.Ollama.v1"
query = {"@llm_queries": "spacy.CallLangChain.v1"}
config = {"model": "llama2", "temperature": 0.0}
```
- Rather than modifying SpaCy's config format, should we maintain a list of known Langchain parameter name for the model's name, and testing them with try/except?

The second one is really dirty, but the first option implies some breaking changes in people's config.

**Comment by florianchappaz** [comment]
For bug reproduction, here is a full `config.cfg`:
```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.NER.v3"
labels = ["PERSON", "ORGANISATION", "LOCATION"]

[components.llm.model]
@llm_models = "langchain.Ollama.v1"
query = {"@llm_queries": "spacy.CallLangChain.v1"}
config = {"model": "llama2", "temperature": 0.0}
```

And a `test.py`:
```from spacy_llm.util import assemble

nlp = assemble("config.cfg")
doc = nlp("I live in France.")

print([(ent.text, ent.label_) for ent in doc.ents])
```

**Comment by rmitsch** [comment]
Hi @florianchappaz, thanks for bringing that up! Yeah, we noticed that [just yesterday](https://github.com/explosion/spacy-llm/issues/372) :upside_down_face: Unfortunately `langchain` changes its API quite often and we have to play catchup.

We are looking into this and will release a patch either later today or beginning of next week.
