### ISSUE TITLE
Plans to support Ollama (or other non-API models)?

### ISSUE THREAD

**Issue by dezoito** [explosion/spacy-llm#413]
Are there any plans to support models hosted on Ollama instances? 
If not, are there any other ways to use locally hosted models?

Say yes, please ; )

**Comment by svlandeg** [comment]
Hi!

We're often adding new models (and tasks) to the core library, but I think it's import to emphasize the fact that you can definitely implement your own as well.

The documentation on how to write your own model is [here](https://github.com/explosion/spacy-llm/tree/main/usage_examples#writing-your-own-model) ;-)

**Comment by dezoito** [comment]
> The documentation on how to write your own model is [here](https://github.com/explosion/spacy-llm/tree/main/usage_examples#writing-your-own-model) ;-)

Thank you for the reply!
I'll check that out.
