### ISSUE TITLE
Bug: Custom Endpoint Validation Breaks Feature Support

### ISSUE THREAD

**Issue by duncangrubbs** [explosion/spacy-llm#426]
In the [v0.7.0](https://github.com/explosion/spacy-llm/releases/tag/v0.7.0) release, the following feature was added

> Allow custom endpoints for all models to support usage of fine-tuned models (https://github.com/explosion/spacy-llm/pull/390)

I am not sure what the exact specification for this feature was, and I filed [an issue](https://github.com/explosion/spacy-llm/issues/387) related to this a few months back, but I am not sure this feature works as expected. For example, the OpenAI REST model still contains [this line](https://github.com/explosion/spacy-llm/blob/main/spacy_llm/models/rest/openai/model.py#L40) which causes an error to be thrown if you pass an endpoint that is not in the [Endpoints](https://github.com/explosion/spacy-llm/blob/main/spacy_llm/models/rest/openai/model.py#L13) enum. For example, if your config looks something like
```
[components.llm_rel.model]
@llm_models = "spacy.GPT-4.v3"
endpoint = YOUR_CUSTOM_ENDPOINT
config = {{"temperature": 0.0}}
"""
```

Am I missing something about how this feature is intended to be used? Thanks! And thanks for the prompt follow-up from my previous issue!

**Comment by rmitsch** [comment]
Thanks for reporting this! Looking into it.
