### ISSUE TITLE
How to load a model that's not supported by spacy RestAPI nor HF?

### ISSUE THREAD

**Issue by pacoBOeT** [explosion/spacy-llm#452]
Hi, 

is there a way to implement in spacy a non supported HF model with langchain? I need to use other models from HF as they progress.
PS: it would be fantastic to have Falcon 40b (not the instruct version) as a supported HF model in spacy_llm. Could it be possible? 

Thank you so much!

**Comment by rmitsch** [comment]
Hi @pacoBOeT, for that please use our `langchain` integration (i. e. use `langchain.MODELNAME.v1`). We likely won't be able to keep up with all the new models coming out and focus on task implementations instead. We will still aim to provide native HF and REST versions of popular models and services, but if you're looking for something we don't offer natively - our `langchain` integration should have you covered.
